---

services:
    - docker

addons:
  apt:
    update: true

install:
  - docker build -f docker/Dockerfile  -t EuroPython/ep-config:$TRAVIS_COMMIT -t EuroPython/ep-config:latest .

script: 
  - docker run EuroPython/ep-config:$TRAVIS_COMMIT tests
